# Generated by Django 3.2.19 on 2023-07-01 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('house_name', models.CharField(max_length=100)),
                ('post_name', models.CharField(max_length=100)),
                ('landmark', models.CharField(max_length=100)),
                ('street_name', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.BigIntegerField()),
                ('image', models.CharField(max_length=400)),
                ('gender', models.CharField(max_length=10)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tvshow_app.login')),
            ],
        ),
        migrations.CreateModel(
            name='Tvshow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('from_time', models.TimeField()),
                ('duration', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('demo_video', models.CharField(max_length=800)),
                ('image', models.CharField(max_length=500)),
                ('Date', models.CharField(max_length=100)),
                ('channelname', models.CharField(max_length=100)),
                ('actors_name', models.CharField(max_length=100)),
                ('actress_name', models.CharField(max_length=100)),
                ('producer_name', models.CharField(max_length=100)),
                ('director_name', models.CharField(max_length=100)),
                ('CATEGORY', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tvshow_app.category')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('review', models.CharField(max_length=100)),
                ('TVSHOW', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tvshow_app.tvshow')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tvshow_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('complaint', models.CharField(max_length=500)),
                ('status', models.CharField(default='pending', max_length=100)),
                ('reply', models.CharField(default='pending', max_length=100)),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tvshow_app.user')),
            ],
        ),
    ]
