# Generated by Django 3.2.19 on 2023-07-05 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvshow_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tvshow',
            name='from_time',
            field=models.CharField(max_length=100),
        ),
    ]
