# Generated by Django 3.2.19 on 2023-07-06 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvshow_app', '0002_alter_tvshow_from_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tvshow',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
