# Generated by Django 3.0 on 2023-07-11 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvshow_app', '0004_auto_20230710_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tvshow',
            name='Date',
            field=models.DateField(max_length=100),
        ),
    ]
